[owner]
name = "ktrueda"

[script]
title = "Share Link in Facebook"
description = """
c.f. 
https://www.hongkiat.com/blog/100-useful-bookmarklets-for-better-productivity-ultimate-list/
"""
target = "http(s)://.*"
body = '''
var d=document,f='http://www.facebook.com/share',l=d.location,e=encodeURIComponent,p='.php?src=bm&v=4&i=1250537391&u='+e(l.href)+'&t='+e(d.title);1;try{if (!/^(.*.)?facebook.[^.]*$/.test(l.host))throw(0);share_internal_bookmarklet(p)}catch(z) {a=function() {if (!window.open(f+'r'+p,'sharer','toolbar=0,status=0,resizable=1,width=626,height=436'))l.href=f+p};if (/Firefox/.test(navigator.userAgent))setTimeout(a,0);else{a()}}void(0)
'''